### ISSUE TITLE
fs引入

### ISSUE THREAD

**Issue by MehJv** [MaLuns/wallhaven-electron#5]
大佬  在vue组件中引入 fs 打印是空对象  我增加了nodeIntegration:true也不行 这个有办法吗
![image](https://user-images.githubusercontent.com/48472208/210056994-feb98591-641e-405b-a5e0-5fe5f6e599bc.png)

**Comment by MehJv** [comment]
![image](https://user-images.githubusercontent.com/48472208/210058066-17376e81-45a4-42a5-8282-cc53817b97d1.png)
在vue.config.js中也配置了  然后我又下载了fs-extra什么都没显示页面报错 TypeError: Cannot read property 'match' of undefined
![image](https://user-images.githubusercontent.com/48472208/210058239-1be62736-d470-4aef-8d9a-7f54c20aed00.png)

**Comment by MaLuns** [comment]
试试将 require 替换成  \_\_non_webpack_require\_\_

**Comment by MaLuns** [comment]
![image](https://user-images.githubusercontent.com/31614024/210084008-ace16694-0c6a-4b31-a856-7ca64f1d386f.png)

**Comment by MehJv** [comment]
大佬我对__non_webpack_require__ 进行了测试报错require is not defined 
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/48472208/210123236-3b4974a9-e0d0-4a5e-862f-e41122ff13d4.png">

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/48472208/210123203-45ef6caa-bf1a-42fa-870b-5cf79ff04365.png">

**Comment by MehJv** [comment]
然后我想到我可能误解你的意思了是不是要给electron添加 然后我进行了尝试程序运行就报错了。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48472208/210123295-ee506106-ed57-4ee5-be5d-c1f816f2c661.png">

**Comment by MaLuns** [comment]
nodeIntegration 这个有设置吗，这个项目前期，前端调用 node api 就是通过这种方式的，[比如这里](https://github.com/MaLuns/wallhaven-electron/blob/a999686d5b914b04682c89bd612c7ac9da9d00fe/layout/src/libs/downfile.js)

**Comment by MaLuns** [comment]
> 然后我想到我可能误解你的意思了是不是要给electron添加 然后我进行了尝试程序运行就报错了。 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48472208/210123295-ee506106-ed57-4ee5-be5d-c1f816f2c661.png">

你这个不是在渲染端啊

**Comment by MehJv** [comment]
> nodeIntegration 这个有设置吗，这个项目前期，前端调用 node api 就是通过这种方式的，[比如这里](https://github.com/MaLuns/wallhaven-electron/blob/a999686d5b914b04682c89bd612c7ac9da9d00fe/layout/src/libs/downfile.js)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48472208/210123457-74140640-9e31-48ae-b7c4-abbb8d4d98eb.png">
我在vue.config.js和window里都进行了设置

**Comment by MehJv** [comment]
> > 然而后来我想到我可能会明白你的意思是不是要给电子添加然而后来我进行了尝试程序运行就报错了。<img alt="图片" width="1440" src="https://user-images.githubusercontent.com/48472208/210123295-ee506106-ed57-4ee5-be5d-c1f816f2c661.png">
> 
> 你这个不是在冲洗端啊

是的，我的问题我对__non_webpack_require__ 没有用到过所有进行了测试

**Comment by MehJv** [comment]
fs和下载的依赖fs-extra在js中引入是可以打印的 就是在vue组件中不行
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48472208/210125230-f74c6fd7-4720-4aed-bc8d-0dc6872b0e53.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48472208/210125292-2ebb6a6e-c514-45c6-96f9-b9d0f4b10445.png">

**Comment by MaLuns** [comment]
> fs和下载的依赖fs-extra在js中引入是可以打印的 就是在vue组件中不行 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48472208/210125230-f74c6fd7-4720-4aed-bc8d-0dc6872b0e53.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48472208/210125292-2ebb6a6e-c514-45c6-96f9-b9d0f4b10445.png">

你这是在主进程，本来就是可以使用

**Comment by MehJv** [comment]
> > fs和下载的依赖fs-extra在js中引入是可以打印的 就是在vue组件中不行 <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48472208/210125230-f74c6fd7-4720-4aed-bc8d-0dc6872b0e53.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48472208/210125292-2ebb6a6e-c514-45c6-96f9-b9d0f4b10445.png">
> 
> 你这是在主进程，本来就是可以使用

大佬 有什么办法可以在不是主进程中也可以使用吗

**Comment by MaLuns** [comment]
![image](https://user-images.githubusercontent.com/31614024/210126374-df211072-039b-4fe4-b7a3-52e2df3a489e.png)
![image](https://user-images.githubusercontent.com/31614024/210126363-5abcd115-06a1-4ee1-b904-d6a828bf4c0a.png)
![image](https://user-images.githubusercontent.com/31614024/210126355-53060de7-43ef-4a67-9443-ff1ebf493021.png)

这样是可以用的，但是项目了 preload.js 里使用了 contextBridge 进行注入的，会和 contextIsolation 冲突，

**Comment by MaLuns** [comment]
你可以通过 preload.js 使用 node api ,而不是直接调用 node api ,也是 electron 推荐做法

![image](https://user-images.githubusercontent.com/31614024/210126686-4c4dd5fb-64a4-4926-9f46-f5121f9e0244.png)
![image](https://user-images.githubusercontent.com/31614024/210126688-f8c1702b-7cf7-45c8-9597-c0e767e342f9.png)

**Comment by MaLuns** [comment]
对于选择哪种方式，就看你个人习惯了

**Comment by MehJv** [comment]
> __non_webpack_require__
好的 感谢🙏

**Comment by MehJv** [comment]
大佬 还有个问题就是前段时间我进行测试的时候  下载列表有正在下载的数据的时候 我点击软件退出。然后从新打开软件下载列表进度不会动了 然后我对不进度下载的中的文件点击删除也删除不了

**Comment by MehJv** [comment]
> 你可以通过 preload.js 使用 node api ,而不是直接调用 node api ,也是 electron 推荐做法
> 
> ![image](https://user-images.githubusercontent.com/31614024/210126686-4c4dd5fb-64a4-4926-9f46-f5121f9e0244.png) ![image](https://user-images.githubusercontent.com/31614024/210126688-f8c1702b-7cf7-45c8-9597-c0e767e342f9.png)

大佬 我按照这个方法挂载window没有挂载上能帮看看吗
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/48472208/210127575-461d0143-9945-44c7-8f1c-b2b5f4544409.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48472208/210127586-34aa6e2a-ebe2-4530-b132-a137fc8fe931.png">

**Comment by MehJv** [comment]
> 你可以通过 preload.js 使用 node api ,而不是直接调用 node api ,也是 electron 推荐做法
> 
> ![image](https://user-images.githubusercontent.com/31614024/210126686-4c4dd5fb-64a4-4926-9f46-f5121f9e0244.png) ![image](https://user-images.githubusercontent.com/31614024/210126688-f8c1702b-7cf7-45c8-9597-c0e767e342f9.png)
大佬 可以了 抱歉我把invokesApi看成invokes了
