### ISSUE TITLE
用户存储

### ISSUE THREAD

**Issue by MehJv** [MaLuns/wallhaven-electron#6]
大佬 不同用户的信息和下载列表应该怎么存，取    我之前的思路是不同的用户创建不同的文件夹进行存储，然后拿当前用户的信息相匹配取对应的文件夹里的信息   我研究了一下electron-store越看越迷了 不知道该怎么去创建对应的用户文件夹了

**Comment by MaLuns** [comment]
electron-store 的 new Store 里有个有个参数是可以指定目录的，你可以通过这处理

![image](https://user-images.githubusercontent.com/31614024/210916206-db1ec2bc-91f6-448a-b6ca-b88c74049bb2.png)

**Comment by MehJv** [comment]
大佬 我获取app.getpath地址然后给app.setpath生成了用户文件夹 但是

**Comment by MehJv** [comment]
大佬 我获取app.getpath地址然后给app.setpath生成了用户文件夹 在项目启的时候已经进行了Store.initRenderer()初始化 我在登录页登录后再进行Store.initRenderer()初始化是不行的   如果登录完不能初始化的话获取下载文件拿不到
![image](https://user-images.githubusercontent.com/48472208/211287631-7c105fb3-19a8-4200-8be6-ab271636b6e2.png)

**Comment by MehJv** [comment]
在项目启动是Store.initRenderer()初始化之前改变是生成了文件夹，下载和下载完毕文件也在yonhuxinxi文件中 
![image](https://user-images.githubusercontent.com/48472208/211288256-91d44b54-d05e-40dc-add5-bf7cdd8b1a2e.png)
![image](https://user-images.githubusercontent.com/48472208/211288583-4a0f8d49-99af-4387-94c0-d385a8653745.png)

**Comment by MehJv** [comment]
我现在是登录完改变了app.getpath地址然后Store.initRenderer()初始化不行  就算把项目启动时的Store.initRenderer()删除也不行，而且因为app.whenReady之前进行了Store.initRenderer()和init的原因，而且app.whenReady和init必须要有一个要不然项目报错显示不出来   有什么办法在点击登录完让Store在初始化一下吗
![image](https://user-images.githubusercontent.com/48472208/211291047-93ff635d-7f71-477a-b190-b466c67e90ab.png)
![image](https://user-images.githubusercontent.com/48472208/211291213-9d115c4d-ed89-43bb-b3c7-b37ce4442bd2.png)

**Comment by MaLuns** [comment]
要动态创建直接使用 electron-store 就可以了吧，你要多用户创建不同文件，可以写个管理  electron-store 创建读取类去处理
![image](https://user-images.githubusercontent.com/31614024/211295965-f610876b-b511-4b35-94ba-a44281a60a5d.png)

**Comment by MehJv** [comment]
> 要动态创建直接使用 electron-store 就可以了吧，你要多用户创建不同文件，可以写个管理 electron-store 创建读取类去处理 ![image](https://user-images.githubusercontent.com/31614024/211295965-f610876b-b511-4b35-94ba-a44281a60a5d.png)

大佬   要是这样的话 
那database.js也会加载所有文件是平级  
如果我是一个新的用户登录的话还是要创建文件这个用户的文件夹吧 但是创建完文件夹Store.initRenderer()初始化不生效  
下载的时候文件还是在外面的文件夹中的这样的话下载列表是取的不对的

**Comment by MaLuns** [comment]
> > 要动态创建直接使用 electron-store 就可以了吧，你要多用户创建不同文件，可以写个管理 electron-store 创建读取类去处理 ![image](https://user-images.githubusercontent.com/31614024/211295965-f610876b-b511-4b35-94ba-a44281a60a5d.png)
> 
> 大佬 要是这样的话 那database.js也会加载所有文件是平级 如果我是一个新的用户登录的话还是要创建文件这个用户的文件夹吧 但是创建完文件夹Store.initRenderer()初始化不生效 下载的时候文件还是在外面的文件夹中的这样的话下载列表是取的不对的

所以需要你写个类去管理 electron-store 动态创建的 Store，每次读写操作需要根据登录用户决定修改对应 Store，项目里的 database.js 和 preload.js 注入到渲染端的 store 都需要调整，是不能直接使用的

**Comment by MehJv** [comment]
恩恩 好的我研究研究 谢谢大佬

**Comment by MehJv** [comment]
大佬 我按照store的方法进行存储 但是我是点击登录的时候才进行的初始化  这样的系统运行的时候取store因为没有初始化报错 而store只能初始化一会   我要拿stron的值是必须要初始化才能拿到
![image](https://user-images.githubusercontent.com/48472208/211459303-82ec8193-72a3-4a64-bc8c-15b4926f7f49.png)
